### ISSUE TITLE
Invalid file with accepted extension Internal Server Error

### ISSUE THREAD

**Issue by mickylindsay** [kikkia/NeuralHashApi#1]
Providing a file with extension png, jpg, or jpeg that is not a valid image returns 500 response. 

Found by createing file called `image (2).png` and writing the plan text value `ayylmao` within it.

https://github.com/kikkia/NeuralHashApi/blob/5b9156937fd34e47619447365e1873023b5205e0/app/main.py#L68-L72

**Comment by kikkia** [comment]
Fixed in https://github.com/kikkia/NeuralHashApi/commit/bcef3bf72a3b41a3c5e0e35b6781ab52053bbb7c
Thank you kind soul for the bug report
